apiVersion: v1
kind: Endpoints
metadata:
  name: test
  namespace: monitoring
  labels:
    app: plarail2021-test
subsets:
- addresses:
  - ip: internal.chofufes2021.gotti.dev
  ports:
  - name: prom
    port: 443
    protocol: TCP
