apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: monitoring
  labels:
    app: plarail2021-test
spec:
  externalName: internal.chofufes2021.gotti.dev
  ports:
  - name: prom
    port: 80
    protocol: TCP
    targetPort: 443
  type: ExternalName
