name: Deploy WebRTC test

defaults:
  run:
    working-directory: ./frontend

on:
  push:
    branches: [ deployment ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'

      - name: npm build
        run: |-
          npm install
          npx webpack

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile.nginx
          platforms: linux/amd64
          push: true
          tags: ghcr.io/ueckoken/plarail2021-soft-frontend:latest
