name: WebRTC test

defaults:
  run:
    working-directory: ./frontend

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
          cache-dependency-path: ./frontend/yarn.lock
      - name: dependency-install
        run: yarn install --frozen-lockfile --immutable
      - name: lint
        run: yarn lint
  buildTest:
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v2
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: ./frontend/
          file: ./frontend/Dockerfile
          platforms: linux/amd64
          push: false
          tags: ghcr.io/ueckoken/plarail2022-frontend:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
