name: WebRTC test

defaults:
  run:
    working-directory: ./frontend

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
          cache-dependency-path: ./frontend/yarn.lock
      - name: dependency-install
        run: yarn install --frozen-lockfile --immutable
      - name: lint
        run: yarn lint
      - name: build
        run: yarn build
